### ISSUE TITLE
Anfrage Zusammenarbeit mit Hyphenopoly

### ISSUE THREAD

**Issue by mnater** [AndreasFerdinand/Syllable.js#1]
Guten Tag Andreas

Da meine Söhne gerade lesen lernen, kam ich auf die Idee einen Silbenschriftkonverter zu programmieren - und dann suche ich, ob das nicht schon jemand gemacht hat und finde dieses Projekt, das dann auch noch meine eigene Silbentrennbibliothek (Hyphenopoly) verwendet. Schön, wenn sich OSS wieder mal lohnt ;-)

Jetzt ist es ja so, dass Hyphenopoly eigentlich nicht für die Silben- sondern für die Worttrennung am Zeilenende gemacht ist (die deutschen Begriffe sind hier etwas irreführend). Deshalb hast du ja in deinem Silbenschriftkonverter die Möglichkeit eingebaut, eigene Trennungen zu definieren.

Die deutschen Trennmuster werden sehr gut gepflegt (http://projekte.dante.de/Trennmuster/WebHome) und es gibt die Möglichkeit aus der Wortliste auch Trennmuster zu generieren, die (fast) alle/mehr Silben berücksichtigen (z.B. Au-to-ren statt Au-toren). Dies ist eigentlich für den Satz von Gesangstext gedacht, würde aber auch den Usecase eines Silbenschriftkonverters abdecken.

Ich könnte solche Trennmuster für Deutsch generieren und Hyphenopoly entsprechend ergänzen.

Pflegst du Syllable.js noch und würdest entsprechende PR annehmen oder soll ich einfach forken?

Beste Grüsse,
Mathias

**Comment by AndreasFerdinand** [comment]
@mnater: Ich mag die "kleine Welt" ;-) Das Projekt ist etwas eingeschlafen, aber ich habe erst vergangene Woche wieder die Webseite aktualisiert (da es einige Anfragen und Wünsche dazu gegen hat) und möchte auch hier wieder mehr Zeit investieren. Ich bin deshalb für jegliche Unterstützung dankbar. Dem entsprechend nehme ich PRs sehr gerne an.

Mir ist bei dem Projekt nur wichtig, dass es frei verfügbar und werbefrei bleibt.

Danke & Liebe Grüße
Andi

**Comment by AndreasFerdinand** [comment]
Ach ja, du kannst (falls du es nicht schon gefunden hast) den Konverter auch im Browser ausprobieren: https://froeschler.net/Silbenschriftkonverter/

**Comment by mnater** [comment]
Es dauert mal wieder länger. Es gibt eine Komplikation mit dem Webassembly-Compiler (https://github.com/WebAssembly/binaryen/issues/5595). Sobald es da eine Lösung gibt, mache ich den PR.

**Comment by mnater** [comment]
Dieser commit: https://github.com/mnater/Hyphenopoly/commit/120a1e0752a16caca2c0b53e848d59e8c5358538 ermöglicht jetzt deutsche Silbentrennung, die für Syllable.js besser geeignet ist.
Dokumentation ist hier: https://mnater.github.io/Hyphenopoly/Special-use-cases.html#syllabification

Ich weiss noch nicht, wann ich ein neues Release machen kann, damit das dann ohne git geladen werden kann...

**Comment by AndreasFerdinand** [comment]
@mnater: Danke für deine Unterstützung. Habe jetzt das deutsche Beispiel so wie die readme entsprechend angepasst!
